#是否启用签到API(默认关闭,仅在你无法签到的情况下可以手动打开，部分功能暂不支持)
Enable_SignApi: false
#是否启用登录API(默认关闭,仅在你无法登录的情况下可以手动打开)
Enable_LoginApi: false
#签到API(不知道是上什么不要动)
signApi: http://113.44.131.92:2536/bili
#登录API
loginApi: http://113.44.131.92:3333/bili
#开启或关闭使用代理
switchProxy: false
#代理链接，如果代理需要认证，需要在代理地址中包含用户名密码，例如：http://user:pass@host:port
proxyAddress: 'http://127.0.0.1:7890'
#自动签到cron
cron: 0 58 7,12 * * *
#自动弹幕cron
livecron: 19 18,34,49 * * * *
#自动日签卡cron
QQDaily: 22 51 17 * * *
#自动抽群幸运字符cron
luckywordcron: 16 4 15 * * *
#自动节日推送cron
festivalpush: 54 1 8 * * *
#自动弹幕的一言API，只支持响应text
yiyan: http://113.44.131.92:3333/text?wb=yy&type=text
#统计信息API
totalApi: http://113.44.131.92:2536/bili
#报时API
baoshiapi: http://113.44.131.92:3333/bs/zdbs
#是否启动解析
Switchjx: true
#默认解析CK
SESSDATA: 这里可以填写默认解析ck(仅SESSDATA字段即可)，用于解析视频(没有哔站登录的用户，已登录的用户使用自己的)，下面的配置是最大视频发送大小/MB
#最大支持发送视频大小
maxVideoSizeMB: "15"
#幸运字符机器人QQ号
isluckywordBots: []
#幸运字符VIP机器人QQ号(抽3次每群)
isviplists: []
#幸运字符白名单群
luckywordwhites: []
#幸运字符黑名单群
luckywordblacks: []
#未知参数
totalbody: []
#节日推送群聊
festivalgroup: []
#报时群聊
baoshigroup: []
#娶群友的冷却时间(主人除外)
whoisMyWifecdTime: 300
#娶群友的群友信息缓存时间
whoisMyWifecacheTime: 3600
#娶群友时随机选择的群友数(影响成功率)
whoisMyWifemaxMembers: 5
#鉴权请求API需要
Authorization: 'Bearer <access_token>'
#是否直接发送按钮，仅支持TRSS && ICQQ && NapCat，仅9.1.50 ~9.1.65？&& 电脑 可见
sendbutton: true
#按钮类型，仅下面四种，不要自己乱写，可以自己删，发送消息的按钮由4个里面随机
buttonType: ['0','1','3','4']
#QQBot是否开启发送链接，必须使用小叶姐姐的适配器，神秘链接：https://gitee.com/xiaoye12123/Yunzai-QQBot-Plugin
QQBotsendlink: true
#是否开启Nap的娱乐功能，每条文本消息自带99+的回应
Napsendtext: false
#是否开启ICQQ的娱乐功能，每条文本消息自带99+的回应
ICQQsendfacetext: false
#表情id，自己尝试
faceids: []